### ISSUE TITLE
Regression prevent using update to remove an entry from a map [DATACASS-841]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#1007]
**[Luc Boutier](https://jira.spring.io/secure/ViewProfile.jspa?name=luc)** opened **[DATACASS-841](https://jira.spring.io/browse/DATACASS-841?redirect=false)** and commented

When migrating a project from 2.x to 3.x I encountered an issue on map field remove operation in a map.

```java
@Table("contact")
class Contact(
    @PrimaryKeyColumn(name = "account_key", ordinal = 0, type = PrimaryKeyType.PARTITIONED)
    var accountKey: UUID,
    @PrimaryKeyColumn(name = "id", ordinal = 1, type = PrimaryKeyType.PARTITIONED)
    var id: UUID,
    @Column("entity_details")
    var entityDetails: MutableMap<UUID, ContactEntityDetails> = mutableMapOf()
)

// Later in some update method:
val update = Update.RemoveOp(ColumnName.from("entityDetails"), entityId)
val query = Query.query(
    Criteria.where("accountKey").`is`(accountKey),
    Criteria.where("id").`is`(id)
)
return cassandraTemplate.update(query, update, Contact::class.java)
```

 

The update statement generated is the following:

```java
UPDATE contact SET entity_details=entity_details-00000000-0000-4000-9000-000000000002 WHERE account_key=f9b520c9-c928-4360-ae69-90d4373cbd57 AND id=6dd405dc-cfbb-40ec-a626-ec18df63ab6d
```

There is curly braces missing as stated [here](https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useInsertMap.html) 

 And this should be if I'm correct

```java
UPDATE contact SET entity_details=entity_details-{00000000-0000-4000-9000-000000000002} WHERE account_key=f9b520c9-c928-4360-ae69-90d4373cbd57 AND id=6dd405dc-cfbb-40ec-a626-ec18df63ab6d
```

 

 

---

**Affects:** 3.1.2 (2020.0.2)

**Comment by mp911de** [comment]
Hey @LucBoutier, there are a couple of issues here. We didn't expose remove from map as we missed that one. Map value removal is limited to a single element only because the DataStax QueryBuilder API. Let's see whether we can navigate around that limitation.

Deleting map entries works only by specifying the value, not the key. For whatever reason, CQL requires a `DELETE` statement to remove a map entry by key.

**Comment by mp911de** [comment]
That's interesting. `entity_details=entity_details-{'hello'}` removes the entry by key, not by value (as stated in the documentation).

/cc @adutra

**Comment by mp911de** [comment]
This change requires quite some changes, so backporting it only to `3.1.x` and `master`.

**Comment by lucboutier** [comment]
Indeed I got confused by our workaround implementation and past behavior when reading your initial comment and actual documentation again.. That's indeed weird..

Note that our current workaround is to use a prepared statement that we create through the following:

```CachedPreparedStatementCreator.of(
         stmtCache, QueryBuilder.update("contact")
             .remove("entity_details", QueryBuilder.bindMarker("entity_id"))
             .whereColumn("account_key").isEqualTo(QueryBuilder.bindMarker("account_key"))
             .whereColumn("id").isEqualTo(QueryBuilder.bindMarker("id"))
             .ifExists()
             .build()
     ).createPreparedStatement(session)```
