### ISSUE TITLE
QuerydslPredicateExecutor and PagingAndSortingRepository not working [DATACMNS-1708]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#1083]
**[Joel](https://jira.spring.io/secure/ViewProfile.jspa?name=jerez)** opened **[DATACMNS-1708](https://jira.spring.io/browse/DATACMNS-1708?redirect=false)** and commented

QuerydslPredicateExecutor and PagingAndSortingRepository without implementation for spring-data-cassandra;

Exceptions:

No property exists found for type org.springframework.data.querydsl.QuerydslPredicateExecutor.

No property findAll found for type org.springframework.data.repository.PagingAndSortingRepository.

Example:

import org.springframework.data.querydsl.QuerydslPredicateExecutor;

import org.springframework.data.repository.PagingAndSortingRepository;

.....

public interface UserRepository extends PagingAndSortingRepository<User, UserPrimaryKey>, QuerydslPredicateExecutor\<User> {}

---

**Affects:** 2.2.6 (Moore SR6)

**Comment by mp911de** [comment]
There's no Querydsl module for Cassandra hence we can't support Querydsl here.
