### ISSUE TITLE
Null Pointer Exception when User Defined Type is not found.

### ISSUE THREAD

**Issue by boutier** [spring-projects/spring-data-cassandra#1084]
In the following, copy() should not be called when resolveType() fails.

https://github.com/spring-projects/spring-data-cassandra/blob/d68184113c56c4d556015cdf7836cf6060d5c020/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/convert/DefaultColumnTypeResolver.java#L449-L452

```java
		com.datastax.oss.driver.api.core.type.UserDefinedType userType = userTypeResolver.resolveType(identifier)
-				.copy(frozen);

		if (userType == null) {
			throw new MappingException(String.format("User type [%s] not found", identifier));
		}

-		return userType;
+		return userType.copy(frozen);
```

**Comment by mp911de** [comment]
That's clearly a bug. Care to submit a pull request?
