### ISSUE TITLE
Pooling Option in the Cassandra in 3.0.6

### ISSUE THREAD

**Issue by sdabikar** [spring-projects/spring-data-cassandra#1090]
Can you please tell me how spring-data-cassandra handle connection pooling? I am usring spring-data-cassandra 3.0.6 ?
 
**Earlier we used to configure like below** 
public class CassandraConfiguration extends AbstractReactiveCassandraConfiguration {

    @Value("${cassandra.host}")
    private String cassandraHost;

    @Value("${cassandra.connections}")
    private Integer cassandraConnections;

    @Override
    public CassandraClusterFactoryBean cluster() {
        PoolingOptions poolingOptions = new PoolingOptions()
                .setCoreConnectionsPerHost(HostDistance.LOCAL,  cassandraConnections)
                .setMaxConnectionsPerHost(HostDistance.LOCAL, cassandraConnections*2);

        CassandraClusterFactoryBean bean = super.cluster();
        bean.setJmxReportingEnabled(false);
        bean.setPoolingOptions(poolingOptions);
        bean.setLoadBalancingPolicy(new TokenAwarePolicy(new RoundRobinPolicy()));

        return bean;
    }

**But currently in 3.0.6 i don't see any option to configure the pooling option can you please let me know how can i create a connection pooling in the cassandra we are using this ReactiveCassandraTemplate and ReactiveCqlTemplate to execute our queries ?**

**Comment by sdabikar** [comment]
currently we are creating bean by autoconfiguration from the application.yml file and 

spring:
  application:
    name: product-offering-qualification
  codec:
    max-in-memory-size: 10MB
  data:
    cassandra:
      enabled: true
      contactpoints: localhost
      port: 9042
      keyspace-name: mykeyspace
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS
      request:
        timeout: 10s
        consistency: LOCAL_ONE

**Comment by mp911de** [comment]
The configuration for pooling is described in the driver documentation, see https://docs.datastax.com/en/developer/java-driver/4.10/manual/core/pooling/. You should be able to configure a `SessionBuilderConfigurer` to configure driver options.
