### ISSUE TITLE
How to set consistency level on a query basis in Java Spring Data Cassandra Reactive Library

### ISSUE THREAD

**Issue by nidhilogic** [spring-projects/spring-data-cassandra#1095]
I am using Spring Data Cassandra reactive library in Java and using ReactiveCqlTemplate to query ScyllaDB. I have tried using the Repository interface but by annnotating the methods with @Query in Repository, it does not gets converted into PrepartedStaement and hence I used ReactiveCqlTemplate which converts the CQL to PrepareStatement. More details below:

On an application level, we can set consistency level by specifying property as below in the application.properties file

spring.data.cassandra.consistency-level=quorum

My question is how do I specify consistency level on a per-query level using ReactiveCqlTemplate? I am using ReactiveCqlTemplate to query my Scylla DB. The code sample is as below:

 @Autowired
	private ReactiveCqlTemplate template;

	@Override
	public Mono<Template> findTemplate(Channel channel, String id) {
		String query = "select * from task where id = ? and channel = ?";
		
		return template.queryForObject(query,  new RowMapper<Template>() {
		    public Template mapRow(Row row, int rowNum) {
		      Template template = new Template();
		      template.setContent(row.getString("content"));
		      template.setMessageType(row.getString("message_type"));
		      template.setSource(row.getString("source"));
		      template.setSubject(row.getString("subject"));
		      template.setTemplateKey(new TemplateKey(row.getString("id"),
                      Channel.fromString(row.getString(("channel")))));
		      return template;
		    }}, UUID.fromString(id), channel.toString());
	}

Is there an out-of-the-box approach where I can set Consistency level while executing a query withReactiveCqlTemplate and PrepareStatement is needed too?

I understand that if I use Repository I can use annotation @Consistency to set consistency level but then how do I make sure that the CQL queries that are going to DB are preparedStatement?

Please suggest

**Comment by jxblum** [comment]
@nidhilogic - This type of question is more always more appropriate in StackOverflow, using the [#spring-data-cassandra](https://stackoverflow.com/questions/tagged/spring-data-cassandra) tag.  Having said that, it does appear you posted your [question](https://stackoverflow.com/questions/66276452/how-to-set-consistency-level-on-per-query-basis-in-java-spring-data-cassandra-re) there as well.

In short, have a look at:

[`ReactiveCqlTemplate.setConsistencyLevel(:ConsistencyLevel)`](https://docs.spring.io/spring-data/cassandra/docs/3.1.5/api/org/springframework/data/cassandra/core/cql/ReactiveCqlTemplate.html#setConsistencyLevel-com.datastax.oss.driver.api.core.ConsistencyLevel-)

As well as:

[`ReactiveCqlTemplate.setSerialConsistencyLevel(:ConsistencyLevel)`](https://docs.spring.io/spring-data/cassandra/docs/3.1.5/api/org/springframework/data/cassandra/core/cql/ReactiveCqlTemplate.html#setSerialConsistencyLevel-com.datastax.oss.driver.api.core.ConsistencyLevel-)

**Comment by nidhilogic** [comment]
There is a lack of documentation around what you have suggested. Could you please help me with one working example where we are setting consistency level on a per-query basis and CQL getting converted into PreparedStatement as well

@jxblum, please help

**Comment by mp911de** [comment]
When using `ReactiveCqlTemplate`, please create `Statement` objects on the calling side.

```
Statement statement = SimpleStatement.newInstance("…").setConsistencyLevel(…);
```

`Statement` belongs to the Cassandra Driver API.

**Comment by nidhilogic** [comment]
@jxblum 

I tried what you suggested but the query is not getting executed as per the code below. It is somehow not binding the value to the partitionkey. Error is 

Caused by: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Invalid null value for partition key part id

Table Schema:

CREATE TABLE IF NOT EXISTS Template (
  	id text,
	channel text,
	content text,
	message_type text,
	source text,
	subject text,
	created_at timestamp,
	updated_at timestamp,	
	PRIMARY KEY((id, channel)) 
);

@Service
public class TestDao {

	@Autowired
	private ReactiveCqlTemplate template;

	@PostConstruct
	public void init() throws InterruptedException {

		ReactivePreparedStatementCreator creator = getCql();

		Flux<Template> test = template.query(creator, new BeanPropertyRowMapper<>(Template.class));

		System.out.println("Subject " + test.blockFirst().getSubject());
		System.out.println("Source " + test.blockFirst().getSource());

		template.execute(creator).subscribe(resp -> {
			System.out.println(resp);
		});

	}

	private ReactivePreparedStatementCreator getCql() {

		SimpleStatement query = SimpleStatement.builder("select * from template where id = ? and channel = ?")
				.addPositionalValue("REGISTRATION").addPositionalValue("EMAIL")
				.setConsistencyLevel(ConsistencyLevel.ALL).build();

		return (session) -> { return session.prepare(query);};
	}

}
