### ISSUE TITLE
Document Datastax driver version support

### ISSUE THREAD

**Issue by akhaku** [spring-projects/spring-data-cassandra#1096]
Hi, the README indicates that this is built on datastax 3.x, but looking through Jira/some if the issues it looks like it is now based on datastax 4.x as of 3.0.0. Just to confirm, this means that datastax 3.x is incompatible?

**Comment by mp911de** [comment]
Good catch and thanks for bringing this to our attention. We need to update the docs to reflect that Spring Data Cassandra 3.x is based on Datastax driver 4.x
