### ISSUE TITLE
Mapping Map<> with UDT in the value is not supported

### ISSUE THREAD

**Issue by ymdomenech** [spring-projects/spring-data-cassandra#1098]
```
@CassandraType(type = CassandraType.Name.MAP, userTypeName = "udt", typeArguments = {CassandraType.Name.TEXT, CassandraType.Name.UDT})
private Map<String, @Frozen UdtClass> map;
```
this will give a NullPointerException

**Comment by mp911de** [comment]
Can you provide a bit more context on when this happens? Adding a stacktrace would be useful, too.

**Comment by ymdomenech** [comment]
I was planning to do a PR on the weekend because I found the problem but I realized that I have to read some docs before contribute.
