### ISSUE TITLE
Log the log prefix for the current request in Webflux

### ISSUE THREAD

**Issue by sharkwouter** [spring-projects/spring-data-cassandra#1099]
I'm not quite sure how this could be made to work, but in the reactive spring log requests each have their own id which is added to the log messages for the requests. At the moment this does not apply to logs for Cassandra.

An example for this would be something like ``[5c648e38] Response 200 OK``. Here the id is ``[5c648e38]``.

Within an endpoint in Spring it is possible to get this id/log prefix can be accessed like this:

```
@GetMapping("/user")
public Flux<User> test(ServerWebExchange serverWebExchange) {
    return users.findAll().log(serverWebExchange.getLogPrefix());
}
```

This would make this endpoint log the result of the query with the id, but not the query itself. Would it be possible to change this?

**Comment by mp911de** [comment]
In Spring Data we have no request Id concept. Given that we have various entry points (repositories, template API, session factory), where would one start or end. 

I'm under the impression that using Spring Cloud Sleuth would be a better option. Paging @marcingrzejszczak @jonatan-ivanov

**Comment by marcingrzejszczak** [comment]
We already support this (I think) - you can annotate your Spring Data interface with Sleuth annotations (https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/using.html#using-annotations).
