### ISSUE TITLE
How to use PagingState after Cassandra driver 4 adoption

### ISSUE THREAD

**Issue by abhikumarblume** [spring-projects/spring-data-cassandra#1121]
Hello team,

I am trying to use 'CassandraPageRequest.pagingState' but facing issues on accessing it. 
I am not sure how to store it (as it is in ByteBuffer format), So that client can use it in next REST call. I oberved that this changes was done as part of version4 adoption. 

https://github.com/spring-projects/spring-data-cassandra/commit/4ded76da0e77e296394bc79293a2e62d0beedb54#diff-2d985142ebb5afe9445999d8f681c157b63f53400519cd6b7e64b39cb0003db5 

Before adoption of cassandra driver version 4 , we have many examples available like :-
https://stackoverflow.com/questions/50816137/serialization-of-cassandrapagerequest

Could you please provide example on how to use PagingState after Adoption of driver 4 ?

**Comment by mp911de** [comment]
What changed is that the `PagingState` object was dropped by the driver and `CassandraPageRequest` now holds directly a reference to `ByteBuffer pagingState`. You can either use `com.datastax.oss.driver.api.core.cql.PagingState.fromBytes`/`.toString` or encode the buffer to Hex/Base64/… according to your preferred encoding to represent raw bytes.
