### ISSUE TITLE
Not able to store Map<String, List<String>> using spring data cassandra 2.1.5.RELEASE

### ISSUE THREAD

**Issue by Agrawalmahin** [spring-projects/spring-data-cassandra#1132]
I have a user defined type, that has a field of type Map<String, List<String>>, while trying to save an object, we are getting null pointer exception.

public class Sample {
  private String id;
  private String name;
 private SampleUdt sampleUdt;
}

public SampleUdt {
  private String someField;
  private Map<String, List < String > >
}

we are getting NPE in BasicCassandraPersistentProperty
```
switch (type) {
			case MAP:
				assertTypeArguments(annotation.typeArguments().length, 2);
				return DataType.map(CassandraSimpleTypeHolder.getDataTypeFor(annotation.typeArguments()[0]),
						CassandraSimpleTypeHolder.getDataTypeFor(annotation.typeArguments()[1]));
```

this is where we get the npe because of `CassandraSimpleTypeHolder.getDataTypeFor(annotation.typeArguments()[1]));`
this brings in only primitive types for values in map.

**Comment by Agrawalmahin** [comment]
```
@Column
    @com.datastax.driver.mapping.annotations.Column
    private Map<String, List<String>> data;
[com.datastax.driver.core.exceptions.InvalidTypeException: Value data is of type map, not varchar

    @Column
    @com.datastax.driver.mapping.annotations.Column
    @CassandraType(type = Name.MAP, typeArguments = {Name.TEXT, Name.LIST})
    private Map<String, List<String>> data;
[java.lang.NullPointerException: at index 1
```

**Comment by mp911de** [comment]
Care to upgrade to the latest version to check whether the issue persists?

**Comment by Agrawalmahin** [comment]
Hey @mp911de ,
I tried with the latest version of spring data cassandra, it works fine there.
But as you said this is supported from 2.1 version,
can you help me what changes needs to be done from my service side?

**Comment by mp911de** [comment]
Note that `@CassandraType(type = Name.MAP, typeArguments = {Name.TEXT, Name.LIST})` isn't able to reflect the type of the `List` and is rather limiting. Type hints in general should not be required.

I successfully tested the correct behavior against the entire version range from 2.1 up to 3.2.

**Comment by Agrawalmahin** [comment]
So what should be the fix from my side,
as I said earlier, I am not able to. store using 2.1.5.RELEASE version for spring data cassandra

If I provide the type hit it gives NPE,
and if not then it says Value data is of type map, not varchar
