### ISSUE TITLE
Add overloads to `CassandraBatchOperations.insert(…)` accepting `WriteOptions`

### ISSUE THREAD

**Issue by MichalFab** [spring-projects/spring-data-cassandra#1135]
When using CassandraBatchOperations with WriteOptions I get:
`com.datastax.oss.driver.api.core.type.codec.CodecNotFoundException: Codec not found for requested operation: [null <-> org.springframework.data.cassandra.core.cql.ExecutionProfileResolver$$Lambda$1007/555149775]`:

`     WriteOptions ttlOption = WriteOptions.builder().ttl(ttl).build();
        CassandraBatchOperations batchOperations = cassandraTemplate.batchOps();
        batchOperations.insert(entity, ttlOption).execute();`

The exception occurs in the QueryBuilder.class. From what I can see, ExecutionProfileResolver is added to the entity object so mapping does not work properly.

Used version:
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-cassandra</artifactId>
			<version>2.4.6</version>
		</dependency>

**Comment by mp911de** [comment]
`WriteOptions` are only accepted through `insert(Iterable<?> entities, WriteOptions options)`. The method you're calling is `insert(Object... entities)`.

**Comment by mp911de** [comment]
Actually, we could introduce overrides accepting a single entity and options since that seems to be used together on a regular basis.
