### ISSUE TITLE
Cannot write composite key that contains a UDT to `Where`

### ISSUE THREAD

**Issue by samueldlightfoot** [spring-projects/spring-data-cassandra#1137]
When trying to create a query in which the primary key is a composite consisting of a UDT and other fields (i.e. not just a UDT) an error is thrown during the WHERE statement generation.

The issue is 'Cannot resolve DataType for com.datastax.oss.driver.api.core.data.UdtValue'.  

I have replicated this in the MappingCassandraConverterUDTUnitTests::shouldWriteUdtWhereWherePrimaryKeyWithCustomConversions test by modiying the Money class to contain a composite primary key (Currency plus another String property as key) rather than just the Currency UDT.

See failing test changes here: https://github.com/samueldlightfoot/spring-data-cassandra/commit/b68892e3aacfc70e09ed29e27849366f06391d00

Issue tested on version 3.3.0 and 3.1.8.

**Comment by mp911de** [comment]
Thanks for report. Writing an object with a composite key with a UDT to `Where` failed because the writing code didn't use the proper method. Generally writing objects using composite keys with UDTs works. We need to fix the `Where` part.
