### ISSUE TITLE
Add QueryOptions to CassandraTemplate 

### ISSUE THREAD

**Issue by ckuehne** [spring-projects/spring-data-cassandra#1143]
Query options - such as consistency level or serial consistency - are important for read queries in Cassandra.
However, `CassandraTemplate` only offers these options for update, insert, and delete - not for select queries.

Please add the QueryOptions to CassandraTemplate read operations also.

**Comment by mp911de** [comment]
For `select`, please provide `QueryOptions` through the `Query` object:

```java
Query q = Query.query(…).queryOptions(QueryOptions.builder().build());

cassandraTemplate.select(q, Person.class);
```
