### ISSUE TITLE
Kotlin annotates constructor parameters instead of fields since `@Column` was allowed for `@Target(PARAMETER)`

### ISSUE THREAD

**Issue by SarangKanabargi** [spring-projects/spring-data-cassandra#1146]
Kotlin spring boot Cassandra app is ignoring @Column("column_name") annotation while mapping the data class to Cassandra columns. As a result of this querries that are auto-generated for insert and update operations are failing. The same mapping works when the data class is replaced by a pojo. Is this because sping kotlin app includes the jackson dependcies that is perhaps forcing Spring-Data-Cassandra to ignore the value specified in the @Column annotation.

Ex - Cassandra entity 

```kotlin
@Table("person")
data class Person(
    @PrimaryKey("person_id")
    val personId: UUID,
    @Column("first_name")
    val firstName: String,
    @Column("last_name")
    val lastName: String,
    @Column("date_of_birth")
    val dateOfBirth: LocalDate,
    @Column("last_updated_at")
    val lastUpdatedAt: LocalDate
)
```

Error
```
Query; CQL [INSERT INTO person (_dateofbirth_,_firstname_,_lastname_,_lastupdatedat_,person_id) VALUES (?,?,?,?,?)]; Undefined column name dateofbirth;
```

The expected result is that generated query should be 

```
INSERT INTO person (date_of_birth,first_name,last_name,last_updated_at,person_id) VALUES (?,?,?,?,?)
```

**Comment by mp911de** [comment]
The problem stems from Kotlin's annotation detection mechanism that tries to find out, which element (field, method, constructor argument) should be annotated. We introduced the possibility to annotate constructor parameters in the last version and now Kotlin's compiler annotates the constructor argument only.

Your class needs to be declared as:

```kotlin
@Table("person")
data class Person(
    @PrimaryKey("person_id")
    val personId: UUID,
    @field:Column("first_name")
    val firstName: String,
    @field:Column("last_name")
    val lastName: String,
    @field:Column("date_of_birth")
    val dateOfBirth: LocalDate,
    @field:Column("last_updated_at")
    val lastUpdatedAt: LocalDate
)
```

See https://kotlinlang.org/docs/annotations.html#annotation-use-site-targets for further details.

**Comment by SarangKanabargi** [comment]
Thanks, works like a charm
