### ISSUE TITLE
Migrate to Jakarta EE 9

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-cassandra#1169]

**Comment by jxblum** [comment]
@mp911de - I was just reviewing SD Cassandra and I don't see that it use the Java Servlet API anyway in the codebase nor does it declare the `javax.servlet:javax.servlet-api` dependency.

**Comment by jxblum** [comment]
@mp911de - I just realized there are other imports from the Java EE namespace (`javax.`) such as `javax.enterprise` that are probably now part of Jakarta EE 9.

**Comment by jxblum** [comment]
This task is dependent on _**Spring Data Commons**_ `3.0` migration to **Jakarta EE 9**, first.
