### ISSUE TITLE
Support configurable batch types for batch operations

### ISSUE THREAD

**Issue by samueldlightfoot** [spring-projects/spring-data-cassandra#1174]
We regularly use unlogged batches for single partition writes as a performance enhancement to reduce messages sent to Cassandra (and stop the coordinator node being overloaded).  It would be nice to provide support for this via the ReactiveCassandraBatchOperations, which currently strictly supports LOGGED batches.

I may be missing part of the reasoning for strictly supporting logged batches, so feel free to correct me if there is reasoning for this.

**Comment by mp911de** [comment]
Thanks for reaching out. We initially decided to use logged batches as unlogged batches often times are misused and we wanted to guide users towards proper usage. `ReactiveCassandraTemplate` could expose a `batchOps(BatchType)` method to define the batch type. Its imperative counterpart, `CassandraTemplate` should be updated as well.

Would you be interested in submitting a pull request for such a change?

**Comment by samueldlightfoot** [comment]
Hi Mark

Makes sense. Sounds good, I'll submit a PR for this.
