### ISSUE TITLE
Flaky test CriteriaUnitTests#shouldCreateIsInSet and a proposed fix

### ISSUE THREAD

**Issue by LeoYimingLi** [spring-projects/spring-data-cassandra#1197]
- The flakiness in ```CriteriaUnitTests#shouldCreateIsInSet``` https://github.com/spring-projects/spring-data-cassandra/blob/880787ff8841b461c3bff6d0755a485171867a59/spring-data-cassandra/src/test/java/org/springframework/data/cassandra/core/query/CriteriaUnitTests.java#L113-L119 is due to the nondeterministic iteration order of  ```HashSet```. https://github.com/spring-projects/spring-data-cassandra/blob/880787ff8841b461c3bff6d0755a485171867a59/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/query/SerializationUtils.java#L115-L118 https://github.com/spring-projects/spring-data-cassandra/blob/880787ff8841b461c3bff6d0755a485171867a59/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/query/SerializationUtils.java#L130-L134

- We can include all the possible iteration order into consideration to fix the flakiness.  Tentative PR: https://github.com/LeoYimingLi/spring-data-cassandra/pull/2/files

- version of spring data
  SHA: 880787ff8841b461c3bff6d0755a485171867a59

- JVM version
  > openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

- The way to reproduce the flaky test failure:
  - 0.Environment setup: Maven 3.6.0 and Java 1.8.0_292
  - 1.clone the repo:
  ```
  git clone https://github.com/spring-projects/spring-data-cassandra
  cd spring-data-cassandra
  git checkout 880787ff8841b461c3bff6d0755a485171867a59
  ```
  - 2.run with [Nondex tool](https://github.com/TestingResearchIllinois/NonDex) (which explores different behaviors of under-determined APIs and reports test failures)
  ```
  mvn install -pl spring-data-cassandra -am -DskipTests
  mvn -pl spring-data-cassandra edu.illinois:nondex-maven-plugin:1.1.2:debug -Dtest=spring-data-cassandra,org.springframework.data.cassandra.core.query.CriteriaUnitTests#shouldCreateIsInSet
  ```
  - 3.And we can get the test failure screenshot:
![image](https://user-images.githubusercontent.com/46290389/142705832-92c64936-51ca-48ef-897f-f13eadcd4da6.png)

**Comment by mp911de** [comment]
Changing the set to a `LinkedHashSet` preserves iteration order unless the sets encounters duplicate items.

**Comment by LeoYimingLi** [comment]
get it, thank you. 
I think this pr fixed in the suggested way: https://github.com/spring-projects/spring-data-cassandra/pull/1199
