### ISSUE TITLE
Add support for XML based configuration for Reactive Cassandra

### ISSUE THREAD

**Issue by gertjanschouten** [spring-projects/spring-data-cassandra#1205]
Spring Data for Cassandra currently supports XML based configuration via the "http://www.springframework.org/schema/data/cassandra" namespace, as explained [here](https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/#cassandra-connectors.xmlconfig).

However, this does not yet include the Reactive Cassandra classes, such as ReactiveCassandraTemplate. It would be useful to support the reactive equivalents of all the classes that are currently supported by XML configuration. They could be added to the same namespace, or a new namespace and XSD, if that's more convenient.

**Comment by mp911de** [comment]
This is by design and we do not plan to add XML support. XML configuration is feature-complete and only maintained to retain compatibility and fix bugs. We recommend using Java-based configuration. Expect XML-based configuration to be removed in a future major revision.

**Comment by gertjanschouten** [comment]
Okay, we'll switch to Java based config then, thanks!
