### ISSUE TITLE
Pagination adapter in `DefaultBridgedReactiveSession` causes `StackOverflowError`

### ISSUE THREAD

**Issue by jakubskalak** [spring-projects/spring-data-cassandra#1215]
Hey,
Several months ago, on production encountered **StackOverflowError** during some kind of batch job, which task was to go through all records of table and do some computation.

It was using Spring Boot 2.5.4, Spring Data Cassandra 3.2.4, Cassandra Java Driver 4.11.3 and Java 11.0.2.
But problem exist also with newer versions, so it is not related to specific version of Spring Data Cassandra, Cassandra Driver or Java.

Since the problem is not so easy for me to explain clearly, I decided to create simple service reproducing this issue, which hopefully may help with understanding the problem - 
[jakubskalak/spring-data-cassandra-stackoverflow](https://github.com/jakubskalak/spring-data-cassandra-stackoverflow)
Under [README.md](https://github.com/jakubskalak/spring-data-cassandra-stackoverflow#readme) I tried to explain my problem and provided way how to reproduce it locally.

If someone have any questions, please feel free to ask me.

**Comment by mp911de** [comment]
That's fixed now. Care to test against the latest snapshots?

**Comment by jakubskalak** [comment]
Tested against 3.2.9-SNAPSHOT and looks working properly, job has finished his work and no StackOverflow error 😄 
Thanks so much @mp911de!
