### ISSUE TITLE
@Table class is being created in both keyspaces in a multiple cassandra keyspace setup.

### ISSUE THREAD

**Issue by adhamhf** [spring-projects/spring-data-cassandra#1219]
I'm trying to use multiple cassandra keyspaces in my app.  I have read [this issue](https://github.com/spring-projects/spring-data-cassandra/issues/997) and am trying option 1 that @markpollack suggested.

My problem is this...  I have two packages `com.example.foo` and `com.example.bar`.  Each package has an `@Table` class with the same name, `Colorado`.   Our SchemaAction is set to CREATE_IF_NOT_EXISTS.  When the app starts up we see that a CqlTemplate command is created for each `Colorado` class in the `foo` keyspace.  The first one will succeed and the second does not because the table already exists, which is expected.  However, the order of the table creation appears indeterminate so sometimes this causes the wrong table to be created first and our tests will fail because a column that should exist on the table does not.

I think this is happening on [CassandraContextMapping:352](https://github.com/spring-projects/spring-data-cassandra/blob/main/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/mapping/CassandraMappingContext.java#L352).  It does not appear there is a way to keep a table create statement in a specific keyspace.  

Is behaving correctly?  Any suggestions on how to associate an `@Table` with a particular keyspace to prevent this from happening? 

Thanks

**Comment by mp911de** [comment]
Schema management through Spring Data Cassandra has limited capabilities and a general assumption is that all tables reside within the same keyspace. There's no keyspace-awareness for tables and Spring Data cannot know whether the same table name is being used to query different views for the same table.

Schema creation is based on the `MappingContext` by inspecting `initialEntitySet`. All discovered entities (by using the base package for classpath scanning) are considered schema elements. 

I suggest disabling the automatic schema management and creating two `CassandraMappingContext` instances that hold only entities that belong to a specific keyspace. During application startup, you make use of `CassandraPersistentEntitySchemaCreator` to create tables/UDTs for each specific keyspace.
