### ISSUE TITLE
Creating a Keyspace if it does not exist from XML config

### ISSUE THREAD

**Issue by snanduri7** [spring-projects/spring-data-cassandra#1221]
Migrating to Spring data cassandra 3.3.1. Want to know how to create a keyspace using XML config only **_if it does not exist._** 

What I see now is if the keyspace is defined and run the app with XML config 

"Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSession': Invocation of init method failed; nested exception is com.datastax.oss.driver.api.core.servererrors.AlreadyExistsException: Keyspace testkeyspace already exists "

Following two approaches same result.

1)
	<cassandra:session id="cassandraSession" contact-points="${cassandra.host}" port="${cassandra.port}" local-datacenter="datacenter1" keyspace-name="testkeyspace" username="${cassandra.username:cassandra}" password="${cassandra.password:cassandra}" schema-action="CREATE_IF_NOT_EXISTS">
		<cassandra:startup-cql>CREATE KEYSPACE IF NOT EXISTS testkeyspace WITH replication = { 'class' : ${replication.strategy}}</cassandra:startup-cql>
	</cassandra:session>
   
2)
	<cassandra:session id="cassandraSession" schema-action="CREATE_IF_NOT_EXISTS" contact-points="localhost" port="9042" keyspace-name="testkeyspace" local-datacenter="datacenter1" 
						username="cassandra" password="cassandra" cassandra-converter-ref="default_converter" >
		<cassandra:keyspace durable-writes="true" action="CREATE" name="testkeyspace">
			<cassandra:replication class="SIMPLE_STRATEGY" >
				<cassandra:data-center name="datacenter1" replication-factor="1" />
			</cassandra:replication>
		</cassandra:keyspace>
	</cassandra:session>

Thanks

**Comment by mp911de** [comment]
Our schema support is limited to `NONE, CREATE, CREATE_DROP, ALTER`, we do not conditionally create keyspaces. Generally, we recommend creating the keyspace outside of the application s this approach gives you control over the lifecycle along with all the flexibility you need.

`schema-action="CREATE_IF_NOT_EXISTS"` refers to tables and UDTs.
