### ISSUE TITLE
Spring data cassandra must introduce enabled flag

### ISSUE THREAD

**Issue by bhumir81** [spring-projects/spring-data-cassandra#1239]
Currently - one of the way to enable spring data cassandra is to enable config in application.yaml
e.g.
spring.data.cassandra.port or spring.data.cassandra.ssl=false etc 

With this spring automatically starts loading all the configuration like CassandraDataAutoConfiguration, CassandraReactiveDataAutoConfiguration, CassandraReactiveRepositoriesAutoConfiguration - while all this is fine - but what if in certain envs - where I do not want to enable these beans since I do not have cassandra in that env - one option is not to specify spring.data.cassandra* but if I have some common spring.data.cassandra config defined in application.yaml, some overrides at application-stage.yaml or application-dev.yaml but application-prod.yaml -> I just say spring.data.cassandra.enabled = false - then it must not try to load/connect cassandra.

**Comment by mp911de** [comment]
This is a Spring Boot issue, can you file a ticket at https://github.com/spring-projects/spring-boot/issues?
