### ISSUE TITLE
WriteOptions.setTtl(Duration) 0-Value assertion allows >= 0 instead of >0 Duration objects

### ISSUE THREAD

**Issue by thst71** [spring-projects/spring-data-cassandra#1248]
The spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/cql/WriteOptions.java#setTtl(Duration) method has an assertion on `duration.isNegative`, but it must assert for `>0` not `>=0`

The setTtl(long) method is correct.

**Comment by mp911de** [comment]
Good catch. Do you want to submit a pull request to fix the issue?

**Comment by thst71** [comment]
Jepp, I will send you sth, I just forked the project.
