### ISSUE TITLE
WriteOptions.ttl method no longer accepts zero

### ISSUE THREAD

**Issue by duanemay** [spring-projects/spring-data-cassandra#1262]
The method recently changed from 
`Assert.isTrue(!ttl.isNegative(), "TTL must be greater than equal to zero");
`
to 
`Assert.isTrue(!ttl.isNegative() && !ttl.isZero(), "TTL must be greater than equal to zero");
`

 !ttl.isZero() was added, however, 
1. The message reported still makes it sound like 0 should be allowed
2.  The 0 seems to tell the Cassandra driver to disable TTL:
https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateTable.html#tabProp__cqlTableDefaultTTL

It seems like 0 should be allowed, but if not the error message should be corrected.

**Comment by mp911de** [comment]
Thanks for the report. The assertion was broken in a polishing commit.

**Comment by tudormarc** [comment]
Hello @mp911de. I would like to contribute by solving this issue. Is it possible? :)

**Comment by mp911de** [comment]
Thanks for reaching out. Feel free to submit a pull request. Check out our [contribution guide](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc) if you want to read up on contribution details.

**Comment by tudormarc** [comment]
@mp911de just to be sure, do we want to allow 0 in order to be able to disable the TTL? Or is it ok like this and just to change the message?

Thanks

**Comment by mp911de** [comment]
We should allow zero to disable TTL.

**Comment by tudormarc** [comment]
@mp911de PR submitted :)

**Comment by choweiyuan** [comment]
Hi would be good to get this in as this is preventing us from upgrading from Spring Boot 2.6 to Spring Boot 2.7
