### ISSUE TITLE
Mixed case table names are not supported without using deprecated annotation property

### ISSUE THREAD

**Issue by ykozarovitsky-quotient** [spring-projects/spring-data-cassandra#1263]
I have a Cassandra database that uses mixed case table names. E.g. User, Partner. When queries are created from the spring application, the table names are lowercased (user, partner). Cassandra complains that the tables do not exist.

In the Table annotation there is a deprecated property forceQuote. When I set this property as true, the table names are used as they are and surrounded by the quotes. Everything works fine. As I understand the forceQuote was used to double quote reserved names. I am not using reserved names. Why are they lowercased?

I believe this is done in the `org.springframework.data.cassandra.core.mapping.IdentifierFactory`.

**Comment by mp911de** [comment]
This is indeed unfortunate, especially there's no mechanism to preserve letter casing except for setting table/column names yourself through `CassandraPersistentEntity.setTableName(…)`/`CassandraPersistentProperty.setColumnName(…)`. We need to revisit the name derivation to actually preserve letter casing when providing a name and not break existing applications when they use name derivation.

**Comment by mp911de** [comment]
Reclassifying this as bug, because a table name `@Table("\"IAmQuoted\"")` is being rendered as `"""IAmQuoted"""` instead of `"IAmQuoted"`.
