### ISSUE TITLE
Update UDT set not always overwrite object with same hashcode

### ISSUE THREAD

**Issue by RileyJia** [spring-projects/spring-data-cassandra#1282]
Hi, I am fairly new to using this library and I am having this issue with spring-boot-starter-data-cassandra:2.7.0, that the Update function not always overwrites objects in a set, not sure if it's a bug or it's by design.

The table looks like this:
```

@Table("student")
@Data
public class Student implements Serializable {

    @NonNull
    @PrimaryKeyColumn(name = "student_id", ordinal = 0, type = PrimaryKeyType.PARTITIONED)
    private String studentId;

    @Column("registed_classes")
    @CassandraType(type = Name.SET, typeArguments = Name.UDT, userTypeName = "registed_class")
    private Set<@Frozen RegistedClass> registedClasses;

    @NonNull
    @Column("last_update_time")
    private Date lastUpdateTime;

}
```
And the RegistedClass UDT looks like this, it has an `attributes` map which is not included when calculating equals and hashcode so that every class will be in the set only once:

```
@UserDefinedType("registed_class")
@EqualsAndHashCode
public class RegistedClass {

    @NonNull
    @Column("class_id")
    private Integer classId;

    @EqualsAndHashCode.Exclude
    @Column("attributs")
    private Map<String, String> attributes;
}
```
Ths issue I am having is when I try to update one class info in the `registeredClasses` set using this code:

```
public boolean updateRegistedClass(String studentId, RegistedClass classInfo) {
    return cassandraTemplate.update(
        Query.query(where("student_id").is(studentId))
            .queryOptions(UpdateOptions.builder().withIfExists().build()),
        Update.empty().addTo("registedClasses").prepend(classInfo)
            .set("last_update_time", new Date()),
        Student.class);
}
```
Sometimes it got updated but sometimes not.

Let's say if student has this entry:

`student_id: "ABC", registed_Classes:[{class_id: 1, attributes: {"professor": "sss"}}]
`
And I try to update the `registeredClass` object with new professor info, if the new value is "aaa", it got updated, but if the value is "zzz", the value remains "sss" and didn't get updated. I am inserting a new object here not just update the `attribute` map since it's `@frozen`

So my question here is how I can make The Update function always overwrites what's in the set in the above scenario?

Thanks

**Comment by mp911de** [comment]
Cassandra set semantics take the entire value into account, Cassandra doesn't care about hashCode, only about CQL and CQL values.
