### ISSUE TITLE
Return value of `BeforeConvertCallback.onBeforeConvert()` is not used when actually saving

### ISSUE THREAD

**Issue by idemockle** [spring-projects/spring-data-cassandra#1295]
When I create a copy of the entity passed into BeforeConvertCallback.onBeforeConvert(), make changes to the copy, then return the copy, the original entity object is used to generate the insert query instead of the modified copy. I would expect the copy to be used instead, otherwise it's hard for me to see why onBeforeConvert() would return a value.

**Comment by mp911de** [comment]
This is a bug in the `CassandraTemplate` and `AsyncCassandraTemplate` classes where the insert of non-versioned entities is affected.
