### ISSUE TITLE
CassandraExceptionTranslator adds whole CQL statement to the Exception message

### ISSUE THREAD

**Issue by vkorenev** [spring-projects/spring-data-cassandra#1323]
[CassandraExceptionTranslator.buildMessage](https://github.com/spring-projects/spring-data-cassandra/blob/74a9771aae17150fb9c3618ec08d35cad52201b9/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/cql/CassandraExceptionTranslator.java#L176) adds whole CQL statement to the message of the exception being thrown. While this can be helpful for debugging, there are some cases when this causes some problems:
- When writing large blobs to Cassandra, the resulting error message contains the whole blob as hex string and thus can have enormous size overwhelming logging and error reporting systems.
- When writing sensitive data, the values show up in logs and error messages.

Possible solutions:
- Remove CQL statement from the message. In most of the cases the message of the driver exception is enough for troubleshooting. CQL statement can be added as a separate field of the thrown Exception, but not in the message.
- Make adding it configurable (and probably off by default).

**Comment by mp911de** [comment]
Spring aims for providing as much context as possible so you, as the developer, can spot problems easily. You can tweak exception translation behavior by either subclassing `CqlTemplate` and override the `translate(String, String cql, RuntimeException)` method or configure the Template API with a `CqlExceptionTranslator` that suits your needs. All extension points are accessible.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
