### ISSUE TITLE
Batch operations not applied without no errors

### ISSUE THREAD

**Issue by rbleuse** [spring-projects/spring-data-cassandra#1333]
Hello,

we're using spring data cassandra 3.4.1, with a batch operation to write data in two tables, same keyspace

Sometimes the write result `wasApplied` is false but doesn't contain any error in executionInfo list with this code :
```kt
// insert batch to maintain consistency
cassandraTemplate.batchOps()
     .insert(post, postByClub)
     .execute()
     .doOnNext { writeResult ->
           writeResult.executionInfo.forEach { executionInfo ->
                 executionInfo.errors.forEach { error ->
                         log.error("Error encountered on node ${error.key}", error.value)
                 }
           }
      }
      .filter { writeResult -> writeResult.wasApplied() }
      .switchIfEmpty(
           run {
                 log.error("Batch operation was not applied for post $post")
                 Mono.error(Exception("xxx"))
           }
      )
      .map {
             xxxx
      }
```

The only log that is displayed is `Batch operation was not applied for post YYYY`
How can we know what failed ?

**Comment by mp911de** [comment]
Do you happen to use lightweight-transactions? (`IF NOT EXISTS`, `IF …`)? If not, then this is a good question for the Datastax driver team/Cassandra server team.

**Comment by rbleuse** [comment]
No we're not using lightweight-transactions at all

**Comment by mp911de** [comment]
Thanks for your reply. I cannot help you with this one, I suggest reaching out to the Datastax driver team.
