### ISSUE TITLE
Spring in Kotlin, can't create data tables

### ISSUE THREAD

**Issue by SaherAlSous** [spring-projects/spring-data-cassandra#1334]
hello...
I'm using cassandra for spring in kotlin project. and i'm creating the tables using the `@Table` annotation like this
```
@Data
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PRIVATE, force = true)
@Table("ingredients")
data class Ingredients(
    @PrimaryKey
    val id: String,
    val name: String,
    val type: Type
)
```
and i'm loading the initial value of the tables in the `@Configuration` class like this:
```
@Configuration
@EnableCassandraRepositories
class DataInitializer: AbstractCassandraConfiguration() {
 
    @Primary
    fun cqlSession(): CqlSession {
        return CqlSession.builder().build()
    }

    override fun getKeyspaceName(): String {
        return "tacocloud"
    }

    override fun getEntityBasePackages(): Array<String> {
        return arrayOf("sia.tacocloud.data")
    }

    @Bean(autowireCandidate = true)
    fun dataLoader(repo: IngredientsRepository): ApplicationRunner {
        return ApplicationRunner {
            repo.deleteAll()
            repo.save(Ingredients("FLTO", "Flour Tortilla", Type.WRAP))
            repo.save(Ingredients("COTO", "Corn Tortilla", Type.WRAP))
            repo.save(Ingredients("GRBF", "Ground Beef", Type.PROTEIN))
            repo.save(Ingredients("CARN", "Carnitas", Type.PROTEIN))
            repo.save(Ingredients("TMTO", "Diced Tomatoes", Type.VEGGIES))
            repo.save(Ingredients("LETC", "Lettuce", Type.VEGGIES))
            repo.save(Ingredients("CHED", "Cheddar", Type.CHEESE))
            repo.save(Ingredients("JACK", "Monterrey Jack", Type.CHEESE))
            repo.save(Ingredients("SLSA", "Salsa", Type.CHEESE))
            repo.save(Ingredients("SRCR", "Sour Cream", Type.CHEESE))
        }
    }
}
```
inside the `application.properties` file inside the `Resources` i made the configuration like this
```
#Cassandra settings
spring.data.cassandra.keyspace-name = tacocloud
spring.data.cassandra.schema-action = create
spring.data.cassandra.local-datacenter = datacenter1
basic.load-balancing-policy.local-datacenter = datacenter1
spring.data.cassandra.contact-points=127.0.0.1
spring.data.cassandra.port=9042
spring.data.cassandra.username = ***
spring.data.cassandra.password = ***
```
I keep getting this error
>Caused by: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: table ingredients does not exist
>Caused by: org.springframework.data.cassandra.CassandraInvalidQueryException: Query; CQL [TRUNCATE ingredients]; table ingredients does not exist

I'm using these dependencies
```
	implementation("org.springframework.boot:spring-boot-starter-data-cassandra")
	// https://mvnrepository.com/artifact/org.springframework.data/spring-data-cassandra
	implementation("org.springframework.data:spring-data-cassandra:4.0.0")
```
Whats wrong in my implementation, why can't I create the tables?
just to note that when i comment the code related to interacting with the data tables, the server works fine.  until I do any action related to cassandra tables.

any solution?

**Comment by SaherAlSous** [comment]
anyone?

**Comment by SaherAlSous** [comment]
Is there a way to create the data tables using beans? Other than @Table annotations I mean

**Comment by Hsain-98** [comment]
Facing the same problem 🙄🫤

**Comment by SaherAlSous** [comment]
it happened the same with JDBC tables, annotations didn't create any db table... but in jdbc we can create it using `schema.sql`.
one guy advised me to use migration tool to create the tables with it. will study it today and post the results if it works.

**Comment by SaherAlSous** [comment]
@Hsain-98 listen...
I solved it by removing the `@Data` annotation of lombok... try that and tell me what happens... i just kept the `@Table` annotation and it is working now...

**Comment by SaherAlSous** [comment]
@Hsain-98 
https://stackoverflow.com/questions/74832684/spring-in-kotlin-creating-cassandra-tables-doesnt-work
