### ISSUE TITLE
How can set the Ttl when update?

### ISSUE THREAD

**Issue by Tingfing6** [spring-projects/spring-data-cassandra#1378]
boolean res = cassandraTemplate.update(getPrimaryIdAndUserIdQuery(toUserId), update, UserRecentCupidCd.class);
How can I set the expiration time of this data while updating ？I am using spring-data-cassandra:3.0.2.RELEASE and I cannot find how to set the expiration time of this data

**Comment by mp911de** [comment]
You can provide the TTL via `UpdateOptions` on your `Query`:

```
Query q = …;
q = q.queryOptions(UpdateOptions.builder().ttl(Duration.ofSeconds(10)).build());
cassandraTemplate.update(q, update, UserRecentCupidCd.class);
```
