### ISSUE TITLE
Broken links in latest ref docs appendix section

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-data-cassandra#1386]
Navigate to https://docs.spring.io/spring-data/cassandra/docs/current-SNAPSHOT/reference/html/#appendix and you will see several unresolved include directives into spring-data-commons. 

> Unresolved directive in index.adoc - include::../../../../../spring-data-commons/src/main/asciidoc/repository-namespace-reference.adoc[leveloffset=+1] Unresolved directive in index.adoc - include::../../../../../spring-data-commons/src/main/asciidoc/repository-populator-namespace-reference.adoc[leveloffset=+1] Unresolved directive in index.adoc - include::../../../../../spring-data-commons/src/main/asciidoc/repository-query-keywords-reference.adoc[leveloffset=+1] Unresolved directive in index.adoc - include::../../../../../spring-data-commons/src/main/asciidoc/repository-query-return-types-reference.adoc[leveloffset=+1] :leveloffset: +1

I see the same problem in the other spring-data projects (I checked redis, mongodb, jpa)...

- https://docs.spring.io/spring-data/redis/docs/current-SNAPSHOT/reference/html/#appendix
- https://docs.spring.io/spring-data/mongodb/docs/current-SNAPSHOT/reference/html/#appendix
- https://docs.spring.io/spring-data/jpa/docs/current-SNAPSHOT/reference/html/#appendix

The attribute variable to the spring-data-commons is using a relative path (that does not exist):
```
:spring-data-commons-docs: ../../../../spring-data-commons/src/main/asciidoc
```
I see that the framework docs url was fixed in https://github.com/spring-projects/spring-data-cassandra/commit/0f5fb56c4fe03a774e661f5f5e16939894c5668b (`spring-framework-docs` asciidoc var replaced w/ `springDocsUrl`).
Should we do something similar for `springDataCommonsDocsUrl`?

**Question:** Where does `springDocsUrl` come from? I don't see it populated anywhere in this repo.

**Comment by mp911de** [comment]
We no longer build snapshot documentation. The links you see are leftovers from quite some time and linger around. The best would be to remove all snapshot documentation to clean up the issue.

**Comment by mp911de** [comment]
Superseded by #1427
