### ISSUE TITLE
Possible to have single application instance do all DDL updates?

### ISSUE THREAD

**Issue by donahchoo** [spring-projects/spring-data-cassandra#1389]
Hi,

Is it possible in SDC to have a single application instance issue DDL updates one at a time and until schema agreement has been achieved cluster-wide before issuing the next DDL statement?

I think this answer is no, but just checking...

**Comment by donahchoo** [comment]
I think this is a `duh` moment...  just turn off all the automatic DDL changes by default in the main profile then have a profile that enables it and only run that profile on one instance?

**Comment by mp911de** [comment]
You pretty much found out about a potential approach. Limiting activity to a single node requires orchestration. Controlling instances through profiles is a viable option. Another approach could be a cluster-wide lock on a single resource but such an approach, while it doesn't involve manual steps, it bears quite some compexity.
