### ISSUE TITLE
AbstractCassandraConfiguration Not Working with @ServiceConnection CassandraContainer for Tests

### ISSUE THREAD

**Issue by murphye** [spring-projects/spring-data-cassandra#1406]
I am trying to use `CassandraContainer` with `@ServiceConnection` in Spring Boot 3.1. This is a supported configuration, and a Cassandra container spins up no problem.

## Summary

1. `@ServiceConnection`, no `AbstractCassandraConfiguration`: WORKS
2. `@ServiceConnection`, has `AbstractCassandraConfiguration`: DOES NOT WORK
3.  `@DynamicPropertySource`, has `AbstractCassandraConfiguration`: WORKS

## Details

```kotlin
	companion object {
		@JvmStatic
		@Container
		@ServiceConnection
		val cassandra: CassandraContainer<*> = CassandraContainer("cassandra:3.11.2")
	}
```

However, there seems to be a problem using this with `AbstractCassandraConfiguration`, for example:

```kotlin
@Configuration
@EnableCassandraRepositories(basePackages = ["com.acme"])
class CassandraConfig : AbstractCassandraConfiguration() {

   @Value("\${spring.cassandra.port:0}")
    private val port = 0

    override fun getPort(): Int {
        return port
    }

    @Value("\${cassandra.keyspace-name:default}")
    private val cassandraKeyspace: String? = null

    override fun getKeyspaceName(): String {
        return cassandraKeyspace!!
    }

    override fun getKeyspaceCreations(): MutableList<CreateKeyspaceSpecification> {
        return mutableListOf(
            CreateKeyspaceSpecification.createKeyspace(
                cassandraKeyspace!!
            )
            .ifNotExists()
            .with(KeyspaceOption.DURABLE_WRITES, true)
            .withSimpleReplication()
        )
    }
}
```

When using this and running `mvn test` I will get this error:

```
Connection refused: localhost/127.0.0.1:0
```

However, when NOT using `AbstractCassandraConfiguration`,  there is NOT a connection error, as the `port` is propagated correctly for Spring Data Cassandra. 

I also tried `@DynamicPropertySource`, and it DID work successfully.

```kotlin
	companion object {
		@JvmStatic
		@Container
		//@ServiceConnection
		val cassandra: CassandraContainer<*> = CassandraContainer("cassandra:3.11.2")

		@DynamicPropertySource
		fun registerCassandraProperties(registry: DynamicPropertyRegistry) {
			registry.add("spring.cassandra.port", cassandra::getFirstMappedPort)
		}
	}
```

**Comment by mp911de** [comment]
`@ServiceConnection` is a Spring Boot feature, paging @mhalbritter to provide guidance over whether there is something we can do in Spring Data Cassandra to work better with service connections.

Generally, `AbstractCassandraConfiguration` concepts predate Spring Boot and there should be no reason to use `AbstractCassandraConfiguration`. Instead, what is preventing you from using Spring Boot's auto-configuration for Cassandra?

**Comment by mp911de** [comment]
You should get the keyspace creation out of the box with test containers. The only remaining thing would be the creation of CQL objects (tables, indices, UDT's). For CQL, you can either use `SessionFactoryInitializer` or `SessionFactoryFactoryBean` if you want to create tables from mapped entities.

Let me know how this goes for you.

**Comment by sathishnune** [comment]
After Spring Boot 3 upgrade, failed to create a template with different bean name. Any help would be appreciated. 

`@Configuration
@EnableCassandraRepositories
public class TestCassandraConfig extends AbstractCassandraConfiguration {

    @Override
    protected String getKeyspaceName() {
        return "keyspace";
    }

    @Override
    protected String getContactPoints() {
        return "atvd1xdcnd101.dbz.unix:9042,atvd1xdcnd102.dbz.unix:9042,atvd1xdcnd103.dbz.unix:9042";
    }

    @Override
    protected String getLocalDataCenter() {
        return "datacenter1";
    }

    @Override
    @Bean("cassandraHealthCheckSession")
    public CqlSessionFactoryBean cassandraSession() {
        CqlSessionFactoryBean cassandraSession = super.cassandraSession();
        cassandraSession.setUsername("sdefi01");
        cassandraSession.setPassword("?pCzHHE|;{d6");

        return cassandraSession;
    }

    @Bean("cassandraHealthCheckTemplate")
    @Override
    public CassandraAdminTemplate cassandraTemplate() {
        return new CassandraAdminTemplate(getRequiredSession(), requireBeanOfType(CassandraConverter.class));
    }

    @Bean
    @Override
    public SessionFactoryFactoryBean cassandraSessionFactory(CqlSession cassandraHealthCheckSession) {
        return super.cassandraSessionFactory(cassandraHealthCheckSession);
    }

    @Override
    protected CqlSession getRequiredSession() {
        return getBeanFactory().getBean("cassandraHealthCheckSession", CqlSession.class);
    }

    @Override
    protected SessionFactory getRequiredSessionFactory() {
        return this::getRequiredSession;
    }
}`

Error:
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraTemplate' defined in class path resource [com/example/cassandratest/config/TestCassandraConfig.class]: No matching factory method found on class [com.example.cassandratest.config.TestCassandraConfig]: factory bean 'testCassandraConfig'; factory method 'cassandraTemplate()'. Check that a method with the specified name exists and that it is non-static.
`
