### ISSUE TITLE
Missing spread operator in `AsyncCqlOperationsExtensions.queryForObject(…)`

### ISSUE THREAD

**Issue by kirillovsky** [spring-projects/spring-data-cassandra#1434]
Hi. In [commit](https://github.com/spring-projects/spring-data-cassandra/commit/4354de756fea06cf53fc3673de1061d99af9507b) @mp911de use spread operator for `AsyncCqlOperations.queryForObject(cql: String, vararg args: Any, function: (Row, Int) -> T): ListenableFuture<T?>` and `AsyncCqlOperations.query(cql: String, vararg args: Any, function: (Row, Int) -> T): ListenableFuture<List<T>>` extensions in `AsyncCqlOperationsExtensions.kt`. But in extension`inline fun <reified T : Any> AsyncCqlOperations.queryForObject(cql: String, vararg args: Any): CompletableFuture<T?>` spread operator doesn't used. I just faced this problem then migrate from Java `queryForObject` with Class parameter to Kotlin extension `queryForObject` with reified type.
Can you help me? May be i do something wrong?
I use **Kotlin 1.8.20**, **jvm target 17** and **spring-data-cassandra 4.1.3**

**Comment by mp911de** [comment]
That's fixed and backported now.

**Comment by kirillovsky** [comment]
Thanks a lot :)
