### ISSUE TITLE
How to configure Datastax Astra using `AbstractCassandraConfiguration`

### ISSUE THREAD

**Issue by miladamery** [spring-projects/spring-data-cassandra#1447]
Hi, I have an app that is using spring(not spring boot) that requires to connect to Datastax Astra DB. There is a solution in case spring boot is available. but that is not an option for me and I couldn't find out how to do this via AbstractReactiveCassandraConfiguration. Thanks in advance.

**Comment by mp911de** [comment]
`AbstractReactiveCassandraConfiguration` creates a CQL session when configuring beans. 

If you want to build a configuration that is robust against Cassandra absence, then you cannot:

* Use schema support
* A configuration built on `Abstract…CassandraConfiguration`

You also need to provide a `SessionFactory` implementation to defer session creation to a later time.

**Comment by miladamery** [comment]
Thanks but I want to ask if this works. I looked at how spring boot configures CqlSession for Astra Db. There is CqlSessionCustomizer that does the job. The code setup CqlSession via a CqlSessionBuilder doing things like setting contact points, setting keyspace etc but at the end calling the customizer which is the following:
```
@Bean
public CqlSessionBuilderCustomizer sessionBuilderCustomizer(DataStaxAstraProperties astraProperties) {
    Path bundle = astraProperties.getSecureConnectBundle().toPath();
    return builder -> builder.withCloudSecureConnectBundle(bundle);
}
```
Almost same identical code exists in normal spring data cassandra. in `AbstractSessionConfiguration` there is method `SessionBuilderConfigurer`. What happens here is almost the same thing that happens in spring boot. So I wonder if the following does connecting to astra Db:

```
public class ReactiveCassandraConfig extends AbstractReactiveCassandraConfiguration {

    @Value("#{config.getString(\"akka.persistence.journal.keyspace\")}")
    private String keySpace;

    private String connectBundlePath;
    @Override
    protected String getKeyspaceName() {
        return keySpace;
    }

    @Override
    protected SessionBuilderConfigurer getSessionBuilderConfigurer() {
        return sessionBuilder -> sessionBuilder
                .withCloudSecureConnectBundle(Path.of(connectBundlePath));
    }
}
```

**Comment by mp911de** [comment]
Sorry, I misunderstood your question and now that you've posted some code, it made it clear what you're asking for. So `SessionBuilderConfigurer` available on `AbstractSessionConfiguration` and its subclasses is the way to go. 

It makes sense to document `SessionBuilderConfigurer` in our reference documentation to make it easier to find what you were asking for.
