### ISSUE TITLE
Datastax java-driver maven coordinates have changed

### ISSUE THREAD

**Issue by tmoschou** [spring-projects/spring-data-cassandra#1467]
The java-driver has recently been donated by Datastax to The Apache Software Foundation and the Apache Cassandra project.

Apache Cassandra Java Driver 4.18.0 is the first release post-donation of the Java Driver. The maven coordinates have changed from `com.datastax.oss` to `org.apache.cassandra`, while all package names remain the same. Migration of docs and download links on the website are still in progress.

See the [announcement](https://lists.apache.org/thread/mnvf77vs4bxg6z47y5lqxzqytm7ctqc7) to the user@cassandra.apache.org mailing list.

Presumably, as the packages names are the same, users can make use of new artifacts by excluding the transitive dependency on `com.datastax.oss`

```xml
<dependency>
    <groupId>org.apache.cassandra</groupId>
    <artifactId>java-driver-core</artifactId>
    <version>4.18.0</version>
</dependency>
<dependency>
    <groupId>org.apache.cassandra</groupId>
    <artifactId>java-driver-query-builder</artifactId>
    <version>4.18.0</version>
</dependency>
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-cassandra</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.datastax.oss</groupId>
            <artifactId>java-driver-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.datastax.oss</groupId>
            <artifactId>java-driver-query-builder</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by mp911de** [comment]
Thanks for reaching out. We will upgrade to the new coordinates with 4.3 M1.
