### ISSUE TITLE
Allow configuration of `CassandraObservationConvention`

### ISSUE THREAD

**Issue by divyagangigunta123** [spring-projects/spring-data-cassandra#1490]
Hi Team,

I have integrated my spring boot application with cassandra observability. Have configured it and able to push low cardinality metrices to prometheus. But unable to push high cardinality keys to prometheus with the existing code base. 

What all changes need to be done to push high cardinality keys as well ? or Can I convert high cardinality key to low cardinality key and push metrices to prometheus ? 

Can you please allow wiring to CassandraObservationConvention interface ?

Regards,
Divya.G

**Comment by mp911de** [comment]
`CassandraObservationConvention` is deeply buried in `CqlSessionObservationInterceptor` and `ObservableReactiveSession`. Currently, there's no external access available to configure the convention.

We would need a configuration mechanism instead of passing on all the individual parts as method or constructor arguments.

**Comment by divyagangigunta123** [comment]
Can you please let me know how we can add configuration mechanism for assandraObservationConvention ?

**Comment by mp911de** [comment]
Since all classes are package-private, there's nothing you could do except for duplicating our code into your codebase and applying the desired changes there.

**Comment by divyagangigunta123** [comment]
Can you please let me know in which class only low cardinality keys are getting picked ? So, that will duplicate that codebase and modify accordingly for db.statement to be picked under low cardinality keys.
