### ISSUE TITLE
Query doesn't support select elements for map column

### ISSUE THREAD

**Issue by ivan-zaitsev** [spring-projects/spring-data-cassandra#1526]
Query doesn't support select elements for map column.

Example of code:
```
CREATE TABLE data (fields map<VARCHAR, VARCHAR>);
```

```
class Data {
        Map<String, String> fields;
}

CassandraOperations cassandraOperations;

Select query = QueryBuilder.selectFrom("table").all()
        .element("map", QueryBuilder.literal("key1"))
        .element("map", QueryBuilder.literal("key2"));

Data data = cassandraOperations.select(query, Data.class);
```

data object will not have map elements present.

**Comment by ivan-zaitsev** [comment]
As a workaround possible to create custom `Mapper`, but not so easy to make it universal to work with any data model.

**Comment by mp911de** [comment]
The query `SELECT map['key1'],map['key2'] FROM table` isn't supposed to map any keys into `Data.fields` as the property names do not match. In fact, `map['key1']` has no column name. You have to provide a data structure along a query where property names map to column names.
