### ISSUE TITLE
TTL `0`  (zero) not added to `INSERT` statement

### ISSUE THREAD

**Issue by eduardmanda** [spring-projects/spring-data-cassandra#1535]
ttl 0 not working anymore when inserting
`cassandraTemplate.insert(entity, InsertOptions.builder().ttl(0).build())
`

QueryOptionsUtil.addWriteOptions seems to be used and it ignores the ttl as it validates it to be !zero.

**Comment by mp911de** [comment]
We indeed do not propagate the TTL if it is zero. We need to represent an absent TTL in contrast to a zero-ttl. Probably, if we make TTL nullable, we can represent absence of a TTL specification.

**Comment by eduardmanda** [comment]
Do you see any alternative currently? besides writing the statement. 
We have an use case where the table has a default ttl and we want to alter that at insert based on certain conditions
