### ISSUE TITLE
`CassandraAdminTemplate.createTable(…)` does not apply table options

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#359]
**[Jens Rantil](https://jira.spring.io/secure/ViewProfile.jspa?name=jensrantil)** opened **[DATACASS-188](https://jira.spring.io/browse/DATACASS-188?redirect=false)** and commented

Thought I had reported this previously, but couldn't find any mention of it. https://github.com/spring-projects/spring-data-cassandra/blob/ff41674809f2fa27362d361ad78730da1d6ebbd8/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/config/CassandraSessionFactoryBean.java#L99 mentions a TODO for this, so it does not seem to be supported.

Specifically, I'd like to be able to set compaction strategy. This is a showstopper for us to use the SchemaActions functionality that Spring Data Cassandra comes with. Currently I have implemented table creation as a custom repository method.

Let me know if this is a duplicate of preexisting ticket

---

1 votes, 2 watchers

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.
