### ISSUE TITLE
CassandraDataAutoConfiguration.cassandraTemplate(…) declares Operations interface instead of implementation class [DATACASS-600]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#718]
**[Alexandru Cibotari](https://jira.spring.io/secure/ViewProfile.jspa?name=alexcibotari)** opened **[DATACASS-600](https://jira.spring.io/browse/DATACASS-600?redirect=false)** and commented

Hello , I have upgraded my Spring Boot **2.0.5** to **2.1.0.M4**
After dependency upgrade I receive next error

```java
The bean 'cassandraTemplate', defined in class path resource [org/springframework/boot/autoconfigure/data/cassandra/CassandraDataAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [x/y/z/config/cassandra/CassandraConfiguration.class] and overriding is disabled
```

because of my

```java
@Configuration
@EnableConfigurationProperties(CassandraProperties.class)
@EnableCassandraRepositories
public class CassandraConfiguration extends AbstractCassandraConfiguration
```

I can disable Auto configuration with

```java
@SpringBootApplication(exclude = [CassandraDataAutoConfiguration::class])
class Application
```

I think Cassandra Auto Configuration needs to take care in consideration my **AbstractCassandraConfiguration** implementation

---

**Affects:** 2.0.10 (Kay SR10), 2.1 GA (Lovelace), 2.2 M1 (Moore)

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/14795

**Referenced from:** commits https://github.com/spring-projects/spring-data-cassandra/commit/514c4ba55328aff8f1d424486e07ca63456eb48e, https://github.com/spring-projects/spring-data-cassandra/commit/18f5025e6444c9e3b804da561c38f17596409b2c, https://github.com/spring-projects/spring-data-cassandra/commit/9e07f5b4ff0af22b0ab8529f8e7776888493691e

**Backported to:** [2.1.1 (Lovelace SR1)](https://github.com/spring-projects/spring-data-cassandra/milestone/108?closed=1), [2.0.11 (Kay SR11)](https://github.com/spring-projects/spring-data-cassandra/milestone/97?closed=1)

**Comment by cmoonExpedia** [comment]
Still happening in 2.4.1. 

```
@SpringBootApplication(exclude = [CassandraDataAutoConfiguration::class])
@ConfigurationPropertiesScan
class Application @Autowired constructor(private val vertx: Vertx, private val serverVerticle: ServerVerticle) {

    @EventListener(ApplicationReadyEvent::class)
    fun deployVerticles() {
        vertx.deployVerticle(serverVerticle)
    }
}

@Bean
fun cassandraSession(@Autowired properties: CassandraProperties): Session {
    val builder = CqlSession.builder()
    properties.nodes.map { node -> builder.addContactPoint(InetSocketAddress(node, properties.port)) }
    builder.withLocalDatacenter(properties.localDatacenter)
    return builder.build()
}
```

Error message,
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'cassandraSession', defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/hs/rippluence/configuration/AppConfig.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**Comment by mp911de** [comment]
@cmoonExpedia Spring Boot 2.3.x and newer uses the new Cassandra Driver 4.
