### ISSUE TITLE
Add support for programmatic DriverConfigLoader [DATACASS-709]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#826]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATACASS-709](https://jira.spring.io/browse/DATACASS-709?redirect=false)** and commented

We should extend `CqlSessionFactoryBean` with a `DriverConfigLoader` property so the driver can be configured using the `DriverConfigLoader.programmaticBuilder()`

---

**Reference URL:** https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/#programmatic-application-config

**Issue Links:**
- [DATACASS-656](https://jira.spring.io/browse/DATACASS-656) Upgrade to Cassandra Driver 4.3
 (_**"depends on"**_)

**Comment by mp911de** [comment]
We already provide a `SessionBuilderConfigurer` which is sufficient to configure the `SessionBuilder.withConfigLoader(…)` property.
