### ISSUE TITLE
Allow keyspace customization for CassandraPersistentEntity

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#921]
**[lmcdasi](https://jira.spring.io/secure/ViewProfile.jspa?name=lmcdasi)** opened **[DATACASS-751](https://jira.spring.io/browse/DATACASS-751?redirect=false)** and commented

In the data stax 4.5 manual it is indicated that creating session/keyspace (https://docs.datastax.com/en/developer/java-driver/4.5/manual/core/) is an anti-pattern:

"`// Anti-pattern: creating two sessions doubles the number of TCP connections opened by the driver`"

You have a solution that uses the AbstractRoutingSessionFactory that just implement that anti-pattern.

But the data stax driver provides actually two different solutions to avoid having that antipattern.
1. use the setKeypace when creating a Statement - but this is OK only if the version supported if > V4. Which would not be available for all.
2. use the built-in QueryBuilder queries that have the keyspace as a parameter. Example: looking at the QueryBuilder.insertInto - it could be changed to use the keyspace since the insertInto signature allows for a a keyspace & a table name. The Statement builder will then build the query by having the keyspace + "." + tablename.

 

The impacted classes are CassandraTemplate & StatementFactory. I attach example code of above where I test the insertTo successfully.

At the same time, while the framework allows me in CassandraConfig to specify a bean to create a cassandraTemplate that can be different than the default CassandraTemplate it does not allow me to re-use the existing framework classes in order to implement my self a template & statement factory where I can specify the keyspace without being forced to copy them out of the framework.

The keyspace can be kept in a ThreadLocal - using the same principle used for AbstractRoutingSessionFactory .

If we cannot have a template as such in the framework, can we at least have the possibility to implement a CassandraTemplace without being forced to copy a lot of code in order to access the existing framework classes ? The template requires quite a few classes that are private.

This assumes that the keyspace schema are the same.

Thank you

---

**Affects:** 3.0 RC1 (Neumann)

**Attachments:**
- [DalAdminTemplate.java](https://jira.spring.io/secure/attachment/27801/DalAdminTemplate.java) (_6.05 kB_)
- [DalStatementFactory.java](https://jira.spring.io/secure/attachment/27800/DalStatementFactory.java) (_39.27 kB_)
- [DalTemplate.java](https://jira.spring.io/secure/attachment/27799/DalTemplate.java) (_39.87 kB_)

1 votes, 4 watchers

**Comment by mp911de** [comment]
Some good things take a bit longer until we get there. We introduced options to configure the keyspace for `@Table` and `@UserDefinedType` to be applied for schema actions and data interaction. Introducing `TableCoordinate` (see #179) is a too broad brush in terms of the API as the coordinates could be either the name or name and keyspace. We would break almost all signatures accepting the table name (or have to create overrides cluttering the API).

For now, we want to allow specific entities to be qualified for a specific keyspace. By configuring a `KeyspaceProvider` through `StatementFactory` we also allow further customization options.

Special honors go to @tomekl007 and @mipo256 for their contributions.
