### ISSUE TITLE
Pass CodecRegistry to StatementBuilder in CassandraTemplate [DATACASS-822]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#988]
**[Łukasz Świątek](https://jira.spring.io/secure/ViewProfile.jspa?name=l.swiatek)** opened **[DATACASS-822](https://jira.spring.io/browse/DATACASS-822?redirect=false)** and commented

`CassandraTemplate` should pass CodedRegistry (which might have been customized with additional codecs) when building cql statements

 

 

---
No further details from [DATACASS-822](https://jira.spring.io/browse/DATACASS-822?redirect=false)

**Comment by aakashacharya177** [comment]
I am using spring data cassandra 3.1.6 artifact and trying to use custom codec.

The insert method in StatementFactory class is not passing converter/codec registry to the statement builder class and hence insert query is not being formed properly.

StatementBuilder<RegularInsert> builder = StatementBuilder.of(QueryBuilder.insertInto(tableName).valuesByIds(Collections.emptyMap())).bind((statement, factory) -> {
            Map<CqlIdentifier, Term> values = createTerms(insertNulls, object, factory);
            return statement.valuesByIds(values);
        }).apply((statement) -> {
            return (RegularInsert)addWriteOptions((Insert)statement, options);
        });

I am using spring data stax oss driver version 4.9.0

Can you please look into this and let us know if this has been fixed or we have a workaround for the same?
